version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Optional: day/time can be set to reduce noise
      # day: "monday"
      # time: "09:00"
      # timezone: "UTC"
    open-pull-requests-limit: 10
