#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Reproduce soft ECC candidate order from the generator matrices in ecc_const.c.

Print the immutable codebooks; no runtime initialization or external input.
The P25 soft decoder historically enumerates data at positions 2,4,5,6,8..14,
not the hard encoder's 4..14. Keep this order for the final tie breaker.
"""

GOLAY = (0x63A, 0x31D, 0x7B4, 0x3DA, 0x1ED, 0x6CC,
         0x366, 0x1B3, 0x6E3, 0x54B, 0x49F, 0x475)
HAMMING = (0x7F08, 0x78E4, 0x66D2, 0x55B1)
PROVOICE = (0x7AC8, 0x3D64, 0x1EB2, 0x7591)


def golay(data):
    parity = 0
    for i, row in enumerate(GOLAY):
        if data & (1 << (11 - i)):
            parity ^= row
    return (data << 11) | parity


def hamming(data, rows, positions):
    word = sum(((data >> i) & 1) << bit for i, bit in enumerate(positions))
    parity = [bit for bit in range(15) if bit not in positions]
    for p in range(16):
        candidate = word | sum(((p >> i) & 1) << bit for i, bit in enumerate(parity))
        if all((candidate & row).bit_count() % 2 == 0 for row in rows):
            return candidate
    raise ValueError("singular Hamming parity matrix")


def emit(name, width, words):
    print(f"static const mbe_ecc_word{width} {name}[{len(words)}] = {{")
    for i in range(0, len(words), 4):
        print("    " + " ".join(f"MBE_ECC_WORD{width}(0x{w:06x}u)," for w in words[i:i+4]))
    print("};\n")


def main():
    print("// SPDX-License-Identifier: GPL-2.0-or-later")
    print("/* Generated by tools/gen_ecc_codebooks.py; do not edit. */")
    print("/* Private to ecc_soft.c; macros select packed words or byte masks. */")
    print("// clang-format off\n")
    emit("soft_golay", 23, [golay(d) for d in range(4096)])
    emit("soft_hamming", 15, [hamming(d, HAMMING, (2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14))
                             for d in range(2048)])
    emit("soft_provoice", 15, [hamming(d, PROVOICE, tuple(range(4, 15))) for d in range(2048)])

    print("// clang-format on")


if __name__ == "__main__":
    main()
