#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Reproduce soft ECC candidate order from the generator matrices in ecc_const.c.

Print the immutable codebooks; no runtime initialization or external input.
The P25 soft decoder historically enumerates data at positions 2,4,5,6,8..14,
not the hard encoder's 4..14. Keep this order for the final tie breaker.
"""

GOLAY = (0x63A, 0x31D, 0x7B4, 0x3DA, 0x1ED, 0x6CC,
         0x366, 0x1B3, 0x6E3, 0x54B, 0x49F, 0x475)
HAMMING = (0x7F08, 0x78E4, 0x66D2, 0x55B1)
PROVOICE = (0x7AC8, 0x3D64, 0x1EB2, 0x7591)


def golay(data):
    parity = 0
    for i, row in enumerate(GOLAY):
        if data & (1 << (11 - i)):
            parity ^= row
    return (data << 11) | parity


def hamming(data, rows, positions):
    word = sum(((data >> i) & 1) << bit for i, bit in enumerate(positions))
    parity = [bit for bit in range(15) if bit not in positions]
    for p in range(16):
        candidate = word | sum(((p >> i) & 1) << bit for i, bit in enumerate(parity))
        if all((candidate & row).bit_count() % 2 == 0 for row in rows):
            return candidate
    raise ValueError("singular Hamming parity matrix")


def emit(name, words):
    print(f"static const uint32_t {name}[{len(words)}] = {{")
    for i in range(0, len(words), 8):
        print("    " + " ".join(f"0x{w:06x}u," for w in words[i:i+8]))
    print("};\n")


def emit_bits(name, bits):
    """Codeword bit of each bit of the enumeration index (the data value)."""
    print(f"static const uint8_t {name}[{len(bits)}] = {{" + ", ".join(str(b) for b in bits) + "};\n")


def main():
    print("// SPDX-License-Identifier: GPL-2.0-or-later")
    print("/* Generated by tools/gen_ecc_codebooks.py; do not edit. */")
    print("/* Private to ecc_soft.c: packed codewords in enumeration order (bit i of a word")
    print(" * is codeword bit i), then the codeword bit of each bit of the enumeration index. */")
    print("#include <stdint.h>\n")
    print("// clang-format off\n")
    golay_data = tuple(range(11, 23))
    hamming_data = (2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14)
    provoice_data = tuple(range(4, 15))
    emit("soft_golay", [golay(d) for d in range(4096)])
    emit_bits("soft_golay_data", golay_data)
    emit("soft_hamming", [hamming(d, HAMMING, hamming_data) for d in range(2048)])
    emit_bits("soft_hamming_data", hamming_data)
    emit("soft_provoice", [hamming(d, PROVOICE, provoice_data) for d in range(2048)])
    emit_bits("soft_provoice_data", provoice_data)

    print("// clang-format on")


if __name__ == "__main__":
    main()
